### ISSUE TITLE
Enhancement: disable text selection

### ISSUE THREAD

**Issue by Chetan8299** [ArnabChatterjee20k/PickPalette-PaletteFromImage#10]
Websites without text selection feel much better
 
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/167693543/a0b4247e-6f38-46e6-9635-26c30ac3492e)

also disable outlines from navbar
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/167693543/500c9fff-058d-4e21-9190-4a82f80b64ba)

please assign this issue to me under GSSOC'24

**Comment by ArnabChatterjee20k** [comment]
Not any major feature

**Comment by ArnabChatterjee20k** [comment]
Thanks for figuring it out. But I don't think this will be impactful.
So I am closing this issue
