### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [ArnabChatterjee20k/PickPalette-PaletteFromImage#13]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me.

**Comment by ArnabChatterjee20k** [comment]
Fine, dont create only for greetings. 
Why dont you also add unassigning bots and issue templates?

**Comment by sanmarg** [comment]
Sure I'll add the issue and pr templates too.
Could you please elaborate on unassigning bots

**Comment by ArnabChatterjee20k** [comment]
> Sure I'll add the issue and pr templates too. Could you please elaborate on unassigning bots

Suppose anyone is not responding in any of the issues and it has passed 24 hours. So the contributor will automatically get unassinged in the issue

**Comment by ArnabChatterjee20k** [comment]
@sanmarg For the unassigning feature, I am opening another issue

**Comment by sanmarg** [comment]
Could you please add the labels to the issue
