### ISSUE TITLE
[Bug] : Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [ArnabChatterjee20k/PickPalette-PaletteFromImage#17]
**Describe the bug**
- The `shoutouts LeaderBoard` page cannot reposive in Mobile mode.
- This is for `X` direction can be `overflow` outside fo the page.
- please assign me . I can i fix it..  

**To Reproduce**
1. Go to `shoutouts LeaderBoard`
2. Click on Inspect
3. Scroll down to  page

**Expected behavior**
- This is Overflow the content that is user cannot see the full details..
- I expected to responsive of the content

**Screenshots**
![Screenshot from 2024-05-14 13-06-22](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/121082414/52694f39-9f16-4e0f-a182-076915eb96d6)

**Comment by ArnabChatterjee20k** [comment]
The project has no such pages. Which link you are visiting??

**Comment by sivaprasath2004** [comment]
@ArnabChatterjee20k 

![Screenshot from 2024-05-14 13-30-04](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/121082414/cc50207b-c2bb-4eb6-a07b-e008dae194ec)

**Comment by ArnabChatterjee20k** [comment]
This is producthunt.com and our project has relation to their site.
Its a social media app
Don't open issues which are not related to the application

**Comment by ArnabChatterjee20k** [comment]
@sivaprasath2004 
if you wanna work responsive issue then already an issue is created. The issue is #9 
Check that
