### ISSUE TITLE
404 error page 

### ISSUE THREAD

**Issue by Nikhilesh002** [ArnabChatterjee20k/PickPalette-PaletteFromImage#19]
Route not found error page is not present. I will make a seperate page for it.

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/134734453/f19ac01c-dead-48d1-acbc-f9f9429f82e8)

I want to work on this feature. @ArnabChatterjee20k  Please assign me this task with required labels for gssoc24.

**Comment by ArnabChatterjee20k** [comment]
Ok I am assigning this to @Nikhilesh002

**Comment by Nikhilesh002** [comment]
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/134734453/12eb80c9-c488-4ac7-92fd-5ab8045c0f0b)


If this is fine, then I will raise pr

**Comment by Nikhilesh002** [comment]
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/134734453/5b6f3f31-adc1-4fa0-8e91-86b5eebeaf53)

If this is fine, I will raise pr

**Comment by ArnabChatterjee20k** [comment]
Its fine but make it simple and something related to the site.

**Comment by Nikhilesh002** [comment]
ok will do it. and what do you mean by simple??

**Comment by ArnabChatterjee20k** [comment]
> ok will do it. and what do you mean by simple??

simple means , here you can see a lot of text. Don't exagerate it.

**Comment by Nikhilesh002** [comment]
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/134734453/6598b579-945d-4ad7-a5f4-2f0086ee3435)

**Comment by ArnabChatterjee20k** [comment]
Change the design
Look for more

**Comment by Nikhilesh002** [comment]
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/134734453/0754029e-9d64-4816-802f-904927d4febb)

**Comment by ArnabChatterjee20k** [comment]
@Nikhilesh002 due to no updates I am removing you from the assignee

**Comment by nishant0708** [comment]
hey i can make 404 page like these please assign me this issue
![Screenshot 2024-05-10 022357](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/101548649/06e806c8-dfee-49eb-897c-4365ea1f103b)
![Screenshot 2024-05-11 041420](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/101548649/dc76ccb6-b2b5-4817-8a9f-3fb7408ac467)

**Comment by ArnabChatterjee20k** [comment]
@nishant0708 the first one looks good and minimal. First complete the other issues then I will assign you

**Comment by nishant0708** [comment]
Hey @ArnabChatterjee20k I have already raised pr of my assigned task and please assign me this issue so that I can start creating this page 🙏

**Comment by AMISH-KHAN** [comment]
hey @ArnabChatterjee20k I am new to this repo and looking for something easier to get started. Would please assign this one to me.

this what I've made

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/123164129/6e0cbff7-cb81-4fcb-ac6f-c2e15dc6811b)

**Comment by ArnabChatterjee20k** [comment]
> hey @ArnabChatterjee20k I am new to this repo and looking for something easier to get started. Would please assign this one to me.
> 
> this what I've made
> 
> ![image](https://private-user-images.githubusercontent.com/123164129/333831424-dba38dcd-cfd6-4926-bdd0-119b23811c0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDg3MDAsIm5iZiI6MTcxNjcwODQwMCwicGF0aCI6Ii8xMjMxNjQxMjkvMzMzODMxNDI0LWRiYTM4ZGNkLWNmZDYtNDkyNi1iZGQwLTExOWIyMzgxMWMwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNzI2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmNmZWIwOTdjY2JlNGZhNDc5NzllMzkxYWNiMjQ1MThiNzg3NmQxYmJkM2Y4MzlmNDdkMjg2YzUzZTFiZjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lchBWXAst8tkODwdckGHsVjqSpcqwMYkePQ-pTDc-7s)

Cool. I am assigning this issue to you @AMISH-KHAN 
Deadline 24hours
