### ISSUE TITLE
User Cannot see the email text at a time of sign in 

### ISSUE THREAD

**Issue by CoderSwarup** [ArnabChatterjee20k/PickPalette-PaletteFromImage#23]
**Describe the bug**

when the go to sign in page and after adding the email they cannot see their email on the form 
**To Reproduce**
1. Go to sign in page
2. enter email on the email input box 
3. observe the email text not see

**Expected behavior**

**Screenshots**

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/128630311/2a748795-0fb4-4fa5-b2b8-5a899ec6858b)

**Additional context**

please assign me this issue i want to work on this

**Comment by ArnabChatterjee20k** [comment]
@CoderSwarup I am assigning this issue
Update me in 24 hours
