### ISSUE TITLE
Update required (README.md)

### ISSUE THREAD

**Issue by Meetjain1** [ArnabChatterjee20k/PickPalette-PaletteFromImage#28]
Currently Our readme.md file is not looking good 
It is looking like a learn.md file I would suggest to @ArnabChatterjee20k assign me this issue I will create a fully new version of readme file , have created the same in many repository , I am working under gssoc

changes required are missing video of our project , allignment of text , open source section , contributors section , code of conduct, license section , features section and many more I will create a beautiful attracting readme file .

**Comment by ArnabChatterjee20k** [comment]
@Meetjain1 how this gonna impact the project? I think the readme is getting the work done especially in terms of what needs to be get done.
I am closing this issue
You can look other issues which can impact the growth of the project

**Comment by ArnabChatterjee20k** [comment]
> > @Meetjain1 how this gonna impact the project? I think the readme is getting the work done especially in terms of what needs to be get done. I am closing this issue You can look other issues which can impact the growth of the project
> 
> Whenever the new user came to any repository, The first impression is on the readme.md file thats why updating it is very necessary I think , But since you closes this issue so leave it. @ArnabChatterjee20k

I get it but all the the necessary information are already present and I think at the current stage contributing to product will make it more beneficial instead of docs
