### ISSUE TITLE
Adding Email verification 

### ISSUE THREAD

**Issue by AMISH-KHAN** [ArnabChatterjee20k/PickPalette-PaletteFromImage#32]
**Describe the bug**

While signIn or signUp there is no email validation.

**Additional context**

Please assign this issue to me under gssoc

**Comment by ArnabChatterjee20k** [comment]
> **Describe the bug**
> 
> While signIn or signUp there is no email validation.
> 
> **Additional context**
> 
> Please assign this issue to me under gssoc

Can you share a video regarding this? I think this is handled by supabase automatically?

**Comment by AMISH-KHAN** [comment]
yes you're right maybe because of some network issue it didn't happened earlier😅
