### ISSUE TITLE
Adding an About Page

### ISSUE THREAD

**Issue by Hemashree21** [ArnabChatterjee20k/PickPalette-PaletteFromImage#34]
In the footer the About link redirects to the github. I can design an about page to highlight the features of the website and also make it responsive. Here is one of the templates.

![Screenshot 2024-05-24 140808](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/138188163/be047a70-44aa-4710-8a15-148ff4f4901b)

I will change the color and the other stylings according to the template of the project.

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/138188163/afc86657-8583-4c30-bb2e-9a7206ab9551)

@ArnabChatterjee20k can you please assign this to me?

**Comment by ArnabChatterjee20k** [comment]
@Hemashree21 Its actually not required currently
Please look for other issues...
