### ISSUE TITLE
Adding new color themes/styles in src/data/colorPalettes.js 

### ISSUE THREAD

**Issue by SanskritiGupta-03** [ArnabChatterjee20k/PickPalette-PaletteFromImage#38]
Need to add new color themes/ styles for diversity of the data.  Suggest ideas and themes

**Comment by ArnabChatterjee20k** [comment]
> Need to add new color themes/ styles for diversity of the data. Suggest ideas and themes

The whole palette adding is getting done automatically through the backend
Everyday around 18 new palettes are added
