### ISSUE TITLE
Getting More Information in SignUp Page 

### ISSUE THREAD

**Issue by narayani9120** [ArnabChatterjee20k/PickPalette-PaletteFromImage#39]
The login and signup pages contain similar information, but the signup page allows us to collect additional details about the user, such as their preferences, contact information, and demographic data, enhancing the user profile for personalized experiences.
![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/125353066/add5c198-ecbb-42f6-8db7-fbbd56a49d35)

Assign this issues to me , under the gssoc

**Comment by ArnabChatterjee20k** [comment]
> The login and signup pages contain similar information, but the signup page allows us to collect additional details about the user, such as their preferences, contact information, and demographic data, enhancing the user profile for personalized experiences. ![image](https://private-user-images.githubusercontent.com/125353066/336037225-add5c198-ecbb-42f6-8db7-fbbd56a49d35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjM0MDAsIm5iZiI6MTcxNzQyMzEwMCwicGF0aCI6Ii8xMjUzNTMwNjYvMzM2MDM3MjI1LWFkZDVjMTk4LWVjYmItNDJmNi04ZGI3LWZiYmQ1NmE0OWQzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxMzU4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjhiNTE5OGY2NDcxNmNiYzE2ZWRhOTk1ZmVlMzlmM2U0MjVkM2I2NWVlYTJlYjc5OWZhOWY3MDJlYTZjYzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yHEvmIYIT682QoJs0OULafhhoZahIvqZbTXH5RE6a7s)
> 
> Assign this issues to me , under the gssoc

whats the plan? Like what things you wanna collect for what purposes

**Comment by SanskritiGupta-03** [comment]
@narayani9120 Any updates on the issue? I'm one of the mentors of the project. Revert back in 24 hours or I'll be bound to unassign you.

**Comment by narayani9120** [comment]
By collecting the user's name during signup, we can display their full name on the dashboard, creating a more personalized experience. Additionally, by gathering the date of birth, we can ensure that the user meets the minimum age requirement, and we can use this information to send birthday greetings or special offers. Furthermore, including a checkbox for users to agree to the terms of service and privacy policy helps ensure compliance and user consent.

**Comment by ArnabChatterjee20k** [comment]
> By collecting the user's name during signup, we can display their full name on the dashboard, creating a more personalized experience. Additionally, by gathering the date of birth, we can ensure that the user meets the minimum age requirement, and we can use this information to send birthday greetings or special offers. Furthermore, including a checkbox for users to agree to the terms of service and privacy policy helps ensure compliance and user consent.

It's not required currently and will break the previous users credentials
