### ISSUE TITLE
Adding Installation And Setup guide

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [ArnabChatterjee20k/PickPalette-PaletteFromImage#43]
I've noticed your project lacks a Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully.
I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

I've done a readme file for another project, you can check my profile, i always give my best.

Can you assign me this task?

Thank u @ArnabChatterjee20k

**Comment by ArnabChatterjee20k** [comment]
@iamkanhaiyakumar go through the readme, setup guide is already present.

**Comment by iamkanhaiyakumar** [comment]
But there no specific code or anything that are help to contributer to clone the repo and setup it this cause I open it

**Comment by iamkanhaiyakumar** [comment]
![Screenshot_2024-06-07-01-06-37-929_com android chrome](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/120328606/a0972416-1826-4941-a383-f46100485574)
This is only documentation not perfect installation and setup guide, I see many contributor that are beginner they have not understand how they setup and installed repo. 
This cause I open this issue. 
However if you have confident that this documentation are proper then I am really sorry for that. 
Thank you @ArnabChatterjee20k

**Comment by ArnabChatterjee20k** [comment]
> ![Screenshot_2024-06-07-01-06-37-929_com android chrome](https://private-user-images.githubusercontent.com/120328606/337412692-a0972416-1826-4941-a383-f46100485574.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDY0MTIsIm5iZiI6MTcxNzcwNjExMiwicGF0aCI6Ii8xMjAzMjg2MDYvMzM3NDEyNjkyLWEwOTcyNDE2LTE4MjYtNDk0MS1hMzgzLWY0NjEwMDQ4NTU3NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMDM1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjdkMTk4YWNkN2EwNTI5NjQ2M2VmMWJmODA0ZTdjNDQ1MWRiYWJlN2VhNTI4MzJhMDEzMTg3ZjAzM2QxNmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZiUpJI5GQMZfPOGU4hQabLStD9_vAfFWypbucCaaQGU) This is only documentation not perfect installation and setup guide, I see many contributor that are beginner they have not understand how they setup and installed repo. This cause I open this issue. However if you have confident that this documentation are proper then I am really sorry for that. This is my work:- ![Screenshot_2024-06-07-01-12-39-438_com android chrome](https://private-user-images.githubusercontent.com/120328606/337414979-d9d7c18a-f2b2-4fec-b979-6bfdceafd55c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MDY0MTIsIm5iZiI6MTcxNzcwNjExMiwicGF0aCI6Ii8xMjAzMjg2MDYvMzM3NDE0OTc5LWQ5ZDdjMThhLWYyYjItNGZlYy1iOTc5LTZiZmRjZWFmZDU1Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMDM1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGRkNTkzMDA5YzBkYzk2M2ExY2RlYzRjZTY3NThiYjBlOWYzMzQzYWJkMDQyMzQyNmZkY2FlM2I1ZmNhNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VaDBrS71MOyuPPL3pf6zqakiu5PUStG23BFlOmCc8_k)
> 
> Thank you @ArnabChatterjee20k

Its fine. I think you should contribute to more of the working parts that gonna create some impact in the application.
Go through the other issues
