### ISSUE TITLE
Addition of Back to Top Button in Website.

### ISSUE THREAD

**Issue by Damini2004** [ArnabChatterjee20k/PickPalette-PaletteFromImage#46]
**Is your feature request related to a problem? Please describe.**
Yes, the request for a "Back to Top" button is related to the problem of user experience on long web pages. When users scroll down through lengthy content, it becomes cumbersome to manually scroll back up to the top. This can be particularly annoying on mobile devices where continuous scrolling can be tedious.

**Describe the solution you'd like**
I would like to have a "Back to Top" button added to the website. This button should appear when users scroll down a certain distance and should smoothly scroll the page back to the top when clicked. Key features should include:

Visibility: The button should only appear after the user has scrolled down a significant amount.
Design: It should be unobtrusive but clearly visible, using an icon or text like an upward arrow or "Top".
Positioning: The button should be positioned in a consistent location, such as the bottom right corner of the screen.
Smooth Scrolling: The button should facilitate smooth scrolling back to the top of the page to enhance user experience.

**Describe alternatives you've considered**
Sticky Navigation Bar: Keeping a navigation bar at the top of the page that allows users to click and scroll back to the top. However, this takes up valuable screen space and might not be as intuitive.
Keyboard Shortcuts: Using keyboard shortcuts like the "Home" button to scroll to the top. This solution, however, is not feasible for all devices, especially mobile ones.
Manual Scrolling: Allowing users to scroll manually, which is the current solution but is not user-friendly for long pages.

**Additional context**

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/119414762/57c842eb-59a5-4305-8608-b76713ddc6dc)

Including a "Back to Top" button can significantly improve the user experience, especially for content-heavy websites like blogs, articles, or e-commerce platforms. It's a small feature that can make navigation much easier and more pleasant for users.

**Comment by ArnabChatterjee20k** [comment]
I don't think this feature is required currently. You can go through other issues and even you can explore the backend repo as well
