### ISSUE TITLE
Addition of Multilingiual Feature to the website

### ISSUE THREAD

**Issue by Damini2004** [ArnabChatterjee20k/PickPalette-PaletteFromImage#47]
**Is your feature request related to a problem? Please describe.**
Our website currently supports only one language, which limits its accessibility and usability for non-native speakers. This language barrier can lead to frustration for users who are not proficient in the website's default language, potentially reducing user engagement and satisfaction.

**Describe the solution you'd like**
To enhance user experience and broaden our user base, we want to add a multilingual feature to our website. This feature should allow users to select their preferred language from a list of available options and have the website's content dynamically translated into that language.

**Describe alternatives you've considered**
User Experience: The solution should provide a seamless and intuitive experience for users across all languages.
Quality of Translations: Translations must be accurate and contextually appropriate.
Cost: Consideration of both initial implementation and ongoing maintenance costs.
Scalability: The solution should be scalable to accommodate more languages as the website grows.
SEO Impact: Ensure that the multilingual setup does not negatively affect SEO and ideally improves it.

**Additional context**

![image](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/assets/119414762/431be499-204f-4e95-8b2a-effb84c3094a)

**Comment by ArnabChatterjee20k** [comment]
I don't think this feature is required currently. You can go through other issues and even you can explore the backend repo as well
