### ISSUE TITLE
[Feat]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [ArnabChatterjee20k/PickPalette-PaletteFromImage#52]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/apu52/METAVERSE/assets/73957207/4c6889aa-3abf-485d-9c41-09f1f562a0aa)

- and issue templates:

![image](https://github.com/apu52/METAVERSE/assets/73957207/6827e4a8-5382-4376-bbf6-afb9f9731252)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by ArnabChatterjee20k** [comment]
@TonyStark-47 not a major issue

**Comment by TonyStark-47** [comment]
> @TonyStark-47 not a major issue

Then why don't you let me contribute. It is not going to waste your time.

**Comment by ArnabChatterjee20k** [comment]
@TonyStark-47 first of all behave properly.
Maintain open source decorums. Try to contribute on issues or features which will impact the growth of the project.
My concern about this project is not about documentation fixing or some automations for prs, the whole concern is on ui ux and optimicity. If you wanna write some automations for growth of the project then do some backend automations for setuping the project backend in one script based on different platforms and os.
Don't behave in a such a way which can force me to talk to the organisers or post it on social media.
I am also an oss contributor and respect the project intentions and also issues algo get closed if it's not required. Behave properly and maintain rules and decorums.
