### ISSUE TITLE
Image size when upload 

### ISSUE THREAD

**Issue by thaisleao** [ArnabChatterjee20k/PickPalette-PaletteFromImage#59]
**Describe the bug**
When uploading an image, it doesn't show proportionally.

**To Reproduce**
1. Go to Home
2. Click on Product > Generate > Upload > Select image file
3. See error

**Expected behavior**
The uploaded image should load proportionally.

**Screenshots**
<img width="1499" alt="image" src="https://github.com/user-attachments/assets/68a53bea-0dd8-469a-bdc2-479e7d13a01f">

**Comment by ArnabChatterjee20k** [comment]
@thaisleao can you fix and raise a pr?
I will merge. Some aspect ratio work will be needed

**Comment by thaisleao** [comment]
Sure! 😉
