### ISSUE TITLE
Chrome Extention - Palette generation from site 

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [ArnabChatterjee20k/PickPalette-PaletteFromImage#8]
Build a chrome extension version to take snapshot of a page and generate palette from it.

**Comment by NIKHIL0VERMA** [comment]
hey @ArnabChatterjee20k,

**Comment by ArnabChatterjee20k** [comment]
Ok I am assigning this issue to @NIKHIL0VERMA 
Update me the implementation plan within 24 hours. Keep updating me every 24 hours. Otherwise it will get unassigned

**Comment by ArnabChatterjee20k** [comment]
@NIKHIL0VERMA 
If possible make sure to track what sites are getting scanned.
Are you comfortable writing a supabase function for it?? If yes I can make take the level to 3.
You have to setup the backend repo as well.
And If you want I can turn this another issue as well.
Just let me know

**Comment by NIKHIL0VERMA** [comment]
> Ok I am assigning this issue to @NIKHIL0VERMA 
> Update me the implementation plan within 24 hours. Keep updating me every 24 hours. Otherwise it will get unassigned

Actually I'm working on almost the same thing 😅. 
So the plan is to have a button Which capture current view port through chrome api. Then use the color thief to get the color palette from the captured image.

**Question**
Where/which folder should I use to store the chrome extension and it's code. Any specific folder name or a new repo.

**Comment by NIKHIL0VERMA** [comment]
> @NIKHIL0VERMA 
> If possible make sure to track what sites are getting scanned.
> Are you comfortable writing a supabase function for it?? If yes I can make take the level to 3.
> You have to setup the backend repo as well.
> And If you want I can turn this another issue as well.
> Just let me know

I think creating an extension itself should be level 3 🥹.

I haven't worked with supabase. But I have a very good experience with firebase. I need to dig into docs.

Could you clarify what it means by writing supabase function and setting up a backend repo?
My understanding: Did you mean that I need to create a repo that connect chrome extension with backend logic and also write function to supabase

**Comment by ArnabChatterjee20k** [comment]
> > @NIKHIL0VERMA
> > If possible make sure to track what sites are getting scanned.
> > Are you comfortable writing a supabase function for it?? If yes I can make take the level to 3.
> > You have to setup the backend repo as well.
> > And If you want I can turn this another issue as well.
> > Just let me know
> 
> I think creating an extension itself should be level 3 🥹.
> 
> I haven't worked with supabase. But I have a very good experience with firebase. I need to dig into docs.
> 
> Could you clarify what it means by writing supabase function and setting up a backend repo? My understanding: Did you mean that I need to create a repo that connect chrome extension with backend logic and also write function to supabase

Supabase functions are similar to firebase cloud functions. Think it like a function which is returning an api and starting that api. If you go more deep, generally it's not rest API rather it's an RPC api at the internal level of supabase.
Let's not make it over complicated and let's keep it only the extension part. I will make a separate issue for backend.
Anyways, I am upgrading the issue to level 3. Thanks me later

**Comment by NIKHIL0VERMA** [comment]
Hey @ArnabChatterjee20k,
Thanks for making it level3.
Here is the testing version of extension. Waiting for feedback.
[Web2palette.zip](https://github.com/ArnabChatterjee20k/PickPalette-PaletteFromImage/files/15285357/Web2palette.zip)

>**Question**
>Where/which folder should I use to store the chrome extension and it's code. Any specific folder name or a new repo?
Asking this as the whole repo is the react project and I don't want to mess up the folder structure. 
Generally, we use the project structure but these two things are different (React and Chrome extension)

**Comment by ArnabChatterjee20k** [comment]
Dont share zip. I created a repo.
Push your code here https://github.com/ArnabChatterjee20k/PickPalette-ChromeExtension

**Comment by NIKHIL0VERMA** [comment]
> Dont share zip. I created a repo. Push your code here https://github.com/ArnabChatterjee20k/PickPalette-ChromeExtension

Thanks for creating the repo, but I'm afraid that my PR to the new repo will not give me any points under GSSOC.
I have asked for solutions from Program managers but they don't know. Waiting for core members' reply.

Sorry for inconvenience, I suggest creating a new **orphan branch** for Chrome-Extension.

Orphan branches don't share commit history means we can have 2 different independent projects in a single repo. while your other branches will depend on the master branch.


Here are the steps in case.
### Steps

1. Clone the repo at new location.
2. Open folder `cd PickPalette-PaletteFromImage`
3. Create orphan branch `git checkout --orphan Chrome-Extension`
4. For orphan branch git need to clean `git rm -rf .`
5. Commit message `git commit --allow-empty -m "Orphan Branch Created"`
6. Push Orphan branch `git push origin Chrome-Extension`

**Comment by ArnabChatterjee20k** [comment]
Ok I am asking this to the admins.
But if you push the commits to orphan branch , I could not ship it to production as the maintenance will get hard and the contribution will be of no use. And I don't think pushing to different repo will create any issue cause a project can grow. Currently it is having client and backend(data collector, api layer). And with extension , one more layer will be added.
As I did during the hacktoberfest in appwrite. 
Currently push it to the new repo. I will merge the pr if the issue is fine and will link the pr here in this issue.

**Comment by NIKHIL0VERMA** [comment]
@ArnabChatterjee20k Okay, Done check the PR

**Comment by hemanth-kumar-boddeda** [comment]
Hi @ArnabChatterjee20k , have you resolved the issue or do you need my assistance?

**Comment by ArnabChatterjee20k** [comment]
@hemanth-kumar-boddeda no its done already
