### ISSUE TITLE
Home page ui fix

### ISSUE THREAD

**Issue by ArnabChatterjee20k** [ArnabChatterjee20k/PickPalette-PaletteFromImage#9]
Fix the landing page of the home page and make it responsive in all screen sizes
If you wanna propose new home page style , make sure to attach the plans or the wireframe

**Comment by agxmbedi** [comment]
I am Agamjot Singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by ArnabChatterjee20k** [comment]
Ok I am assigning this @agxmbedi

**Comment by ArnabChatterjee20k** [comment]
@agxmbedi You have to update within 24 hours how you are planning to implement it can complete it within 48 hours
If no updates given it will get unassigned

**Comment by agxmbedi** [comment]
alright sir

**Comment by ArnabChatterjee20k** [comment]
@agxmbedi any updates??

**Comment by ArnabChatterjee20k** [comment]
@agxmbedi Removing you from the assignee due to no updates

**Comment by linhphan03** [comment]
@ArnabChatterjee20k Under GSSoC, can you assign it to me? I'll update it in 24hrs

**Comment by nishant0708** [comment]
hey i can fix this issule.please assign it to me under gssoc24

**Comment by ArnabChatterjee20k** [comment]
Ok I am assigning this issue to @nishant0708
Fix the responsiveness
Update me every 24hrs
